### PR TITLE
Remove wrapper double spacing

### PR DESCRIPTION
**Pull request by solidgoldpig**
Before

GOV_UK_-_The_best_place_to_find_government_services_and_information

After

GOV_UK_-_The_best_place_to_find_government_services_and_information

Also bumped govuk_frontend to 2.10.0 (no changes other than adding a small radios class)

### CODE REVIEW

**Review by umaar — APPROVED** [review]
Looks good but could you shed a little light on the `fb-main-grid-wrapper` change? And what was the effect of the old `govuk-main-wrapper`?

**Comment by solidgoldpig** [comment]
`.fb-main-grid-wrapper` isn't doing anything at the moment, just acting as a hook if we do need it.

The attached images show the effect of the double-wrapping - `.govuk-main-wrapper` has `margin: 40px` on it, doubling to 80px.

**Comment by umaar** [comment]
Thanks but then could we lose the benefits of other styling which `govuk-main-wrapper` would've provided? As in I'm wondering what was doubling the 40px? Because if it were our own styling, maybe we could remove that and rely on theirs?

I'm probs misunderstanding things!

**Comment by solidgoldpig** [comment]
We still have the `. govuk-main-wrapper` on the main element. So we're not losing it ;) We literally had one inside another - I have changed the nested one to the `.fb-main-grid-wrapper`

**Comment by umaar** [comment]
Makes sense! Thanks for explaining  👍️

**Pull request merged**
