### PR TITLE
remove accept attribute from file upload

### PR DESCRIPTION
**Pull request by asmega**
this way users are free to upload any files they wish
the server will handle the uploaded file and return appropriate error
message back to the user

### CODE REVIEW

**Comment by solidgoldpig** [comment]
Why do you need to remove this attribute?

If you don't set it, then there are no restrictions on what type of files can be uploaded - ie. users are already free to upload any files they wish.

If a form genuinely needs to restrict the file type - ie. just images or pdf, then removing this will prevent default browser behaviour that only allows files of the correct type to be chosen) 

NB. `accepts` maps directly to an actual HTML attribute

**Comment by asmega** [comment]
This liberates the user to upload any file they wish as opposed to constricting them to certain files in the browser. For example a user may want to upload an image even though we only accept PDFs, in this case the won't be allowed to select the image causing them frustration. Whereas if we let them upload the file we can provide the appropriate error message back to the user as feedback

**Review by adamsilver — APPROVED** [review]

**Comment by solidgoldpig** [comment]
Then simply don't set the `accepts` value. Why would you set it to just pdfs if you also accept images?

**Comment by adamsilver** [comment]
Hey Alex—it's because we don't want to disable parts of the interface. Users are left to guess why their dialog has disabled/hidden items.

We want to set the accepts value in the Editor UI, but to have it handled with an error message.

Additionally, to help users avoid selecting invalid files, we'd supply hint text as well.

Of course ideally, we'll accept as many files as possible to suit the question.

**Comment by solidgoldpig** [comment]
Removing the `accept` attribute doesn't achieve that.

Removing the bit in `fileuploads.njk` would

```
  {% if params.accept %}
    {% set attributes = setObject(attributes, {accept: params.accept}) %}
  {% endif %}
```

Then you would still ability to set the `accept` attribute, but not have browsers prevent choosing anything.

**Comment by adamsilver** [comment]
Sounds good to me.

Thanks!
Adam

Website: adamsilver.io
Twitter: @adambsilver <http://www.twitter.com/adambsilver/>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
13/09/19,
11:22:02

**Pull request merged**
